install.packages(c('optimx',
                 'rbenchmark',
                 'knitr',
                 'pryr',
                 'data.table',
                 'rcpp',
                 'ff',
                 'ffbase',
                 'parallel'))